stages:
  - build
  - deploy

buildJob:
  stage: build
  script: 
    - whoami
    - cd src/DoloresNetCore
    - pwd
    - dotnet restore
    - dotnet publish -c ReleaseLinux
  artifacts:
    paths:
      - src/DoloresNetCore/bin/ReleaseLinux/netcoreapp2.1/publish*

deployJob:
  stage: deploy
  script:
    - cp -R src/DoloresNetCore/bin/ReleaseLinux/netcoreapp2.1/publish/* /home/gitlab-runner/ProjectInstances/Dolores/
    - cd /home/gitlab-runner/ProjectInstances/Dolores
    - echo $CI_PIPELINE_ID > version
    - /home/ilddor/Scripts/DoloresDeploy
