build:
  stage: build
  script: 
    - whoami
    - cd src/DoloresNetCore
    - pwd
    - dotnet restore
    - dotnet build
  artifacts:
    paths:
      - src/DoloresNetCore/bin/Debug/netcoreapp2.0/*
