stages:
  - build
  - deploy
#  - cleanup

buildJob:
  stage: build
  script: 
    - whoami
    - cd src/DoloresNetCore
    - pwd
    - dotnet restore
    - dotnet publish -c ReleaseLinux
  artifacts:
    paths:
      - src/DoloresNetCore/bin/ReleaseLinux/netcoreapp2.0/publish*

deployJob:
  stage: deploy
  script:
    - cp src/DoloresNetCore/bin/ReleaseLinux/netcoreapp2.0/publish/* /home/gitlab-runner/ProjectInstances/Dolores/
    - cd /home/gitlab-runner/ProjectInstances/Dolores
    - echo $CI_PIPELINE_ID > version
    - /home/ilddor/Scripts/DoloresDeploy
#- echo $CI_PIPELINE_ID > version
#- ./
#- screen -m -d -L -S Dolores dotnet DoloresNetCore.dll

#cleanupJob:
#  stage: cleanup
#  script:
#- rm -rf *